"""add chat audit logs

Revision ID: 0432ad4c7d83
Revises: d27b82e5ef47
Create Date: 2026-02-21 10:19:47.281796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0432ad4c7d83'
down_revision: Union[str, Sequence[str], None] = 'd27b82e5ef47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_audit_logs_tenant_id'), 'chat_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_audit_logs_user_id'), 'chat_audit_logs', ['user_id'], unique=False)
    op.create_index('ix_chat_audit_tenant_created_at', 'chat_audit_logs', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_audit_tenant_created_at', table_name='chat_audit_logs')
    op.drop_index(op.f('ix_chat_audit_logs_user_id'), table_name='chat_audit_logs')
    op.drop_index(op.f('ix_chat_audit_logs_tenant_id'), table_name='chat_audit_logs')
    op.drop_table('chat_audit_logs')
    # ### end Alembic commands ###
