"""add metrics to chat audit logs

Revision ID: 09eba4ba7c9f
Revises: a53d1c623902
Create Date: 2026-02-21 18:25:33.481347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eba4ba7c9f'
down_revision: Union[str, Sequence[str], None] = 'a53d1c623902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_audit_logs', sa.Column('model', sa.String(length=64), nullable=True))
    op.add_column('chat_audit_logs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('chat_audit_logs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_audit_logs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_audit_logs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_audit_logs', sa.Column('policy_reason', sa.String(length=128), nullable=True))
    op.add_column('chat_audit_logs', sa.Column('retrieval_doc_count', sa.Integer(), nullable=True))
    op.add_column('chat_audit_logs', sa.Column('retrieval_chunk_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_audit_logs', 'retrieval_chunk_count')
    op.drop_column('chat_audit_logs', 'retrieval_doc_count')
    op.drop_column('chat_audit_logs', 'policy_reason')
    op.drop_column('chat_audit_logs', 'total_tokens')
    op.drop_column('chat_audit_logs', 'completion_tokens')
    op.drop_column('chat_audit_logs', 'prompt_tokens')
    op.drop_column('chat_audit_logs', 'latency_ms')
    op.drop_column('chat_audit_logs', 'model')
    # ### end Alembic commands ###
