"""add tenant policies table

Revision ID: e41097d8a029
Revises: 7dbd508bb970
Create Date: 2026-02-21 13:14:54.563948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41097d8a029'
down_revision: Union[str, Sequence[str], None] = '7dbd508bb970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_policies',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('policy_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_policies')
    # ### end Alembic commands ###
